import Head from 'next/head'
import { Inter } from '@next/font/google'
import { FaAngleDoubleDown,FaChalkboardTeacher,FaClock, FaLightbulb, FaRegSmileBeam, FaRocket } from 'react-icons/fa';
import { useEffect, useRef, useState } from 'react';
import Objective from '../components/Objective';
import Image from 'next/image';
import Icon from '../components/Icon';
import About from '../components/About';
import Welcome from '../components/Welcome';
import Skill from '../components/Skill';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const itemref = useRef<HTMLDivElement>(null)
  const aboutref = useRef<HTMLDivElement>(null)
  const portoref = useRef<HTMLDivElement>(null)
  const contactref = useRef<HTMLDivElement>(null)
  const mainref = useRef<HTMLDivElement>(null)
  const navref = useRef<HTMLDivElement>(null)
  const [skill,setSkill] = useState('ALL')
  const [section,setSection] = useState("home")
  const skills = ['ALL','Javascript','Java','SQL','VueJs','ReactJs','NextJs']
  const handleOnClick = ()=>{
    const element = itemref.current
    const mainElement = mainref.current
    mainElement?.scrollTo(0,element? element.clientHeight : 0)
  }
  const handleSelectSKill = (e:string)=>{
    setSkill(e)
  }
  useEffect(()=>{
    const element = itemref.current
    const mainElement = mainref.current
    const navElement = navref.current
    const aboutElement = aboutref.current
    const portoElement = portoref.current
    const contractElement = contactref.current
    let timer = setTimeout(function() {
      mainElement?.classList.add('scrollbar');
      mainElement?.classList.remove("scrollbar2");
    }, 200);
    const handleScroll = (e:Event)=>{
      if(mainElement && element && aboutElement && portoElement && contractElement){
        if (mainElement.scrollTop >=  element.clientHeight + aboutElement.clientHeight + portoElement.clientHeight -2 ){
          setSection("contact")
        }else if(mainElement.scrollTop >= element.clientHeight + aboutElement.clientHeight - 2){
          setSection("portofolio")
        }else if(mainElement.scrollTop >= element.clientHeight-10){
          if(navElement?.classList.contains("relative")){ 
            navElement?.classList.remove("relative")
            navElement?.classList.add("navbar")
          }
          if(mainElement.scrollTop >= element.clientHeight -2 )
            setSection("about")
        }else if(mainElement.scrollTop < element.clientHeight){
          if(navElement?.classList.contains("navbar")){ 
            navElement?.classList.add("relative")
            navElement?.classList.remove("navbar")
            setSection("home")
          }
        }
      }
      mainElement?.classList.remove('scrollbar');
      mainElement?.classList.add("scrollbar2")
      clearTimeout(timer);
      timer = setTimeout(function() {
        mainElement?.classList.add('scrollbar');
        mainElement?.classList.remove("scrollbar2");
      }, 200);  
    }
    mainElement?.addEventListener('scroll', handleScroll, true);
  })
  return (
    <>
      <Head>
        <title>Andy Khu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <svg className='invisible absolute' width="0" height="0" xmlns="http://www.w3.org/2000/svg" version="1.1">
        <defs>
              <filter id="round">
                  <feGaussianBlur in="SourceGraphic" stdDeviation="5" result="blur" />    
                  <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 19 -9" result="goo" />
                  <feComposite in="SourceGraphic" in2="goo" operator="atop"/>
              </filter>
          </defs>
      </svg>
      <main ref={mainref} className="overflow-x-hidden bg-black w-screen h-screen scrollbar scroll-smooth relative">
        <Welcome itemref={itemref} handleOnClick={handleOnClick}/>
        <div ref={aboutref} className='min-h-screen w-screen flex flex-col text-white'>
          <About section={section} navref={navref} refall={{main:mainref,home:itemref,about:aboutref,porto:portoref,contact:contactref}}/>
        </div>
        <div ref={portoref} className='min-h-screen w-screen flex flex-col text-white bg-[#18181b]'>
          <Skill skill={skill} skills={skills} handleSelectSKill={handleSelectSKill}/>
        </div>
        <div ref={contactref} className='min-h-screen w-screen flex flex-col bg-white'>
          <svg preserveAspectRatio="none" viewBox="0 0 100 102" height="120" width="100%" version="1.1" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 0 L0 42 L50 100 L100 42 L100 0 Z" fill="#18181b"></path>
          </svg>
          <div className='flex flex-col justify-center items-center p-8 pt-6'>
                <h1 className='text-4xl font-bold text-[#18181b] relative after:inset-x-4 after:rounded-full after:h-1 after:bg-[#18181b] after:-bottom-5 after:absolute h-12'>CONTACT</h1>
                <p className='mt-10 text-2xl font-bold text-gray-500'>Have a question or want to work together?</p>
          </div>
          <div className='flex justify-center pb-8'>
            <div className='flex flex-col gap-4 w-full md:w-auto px-8 items-center'>
              <input className='p-2 w-full md:w-[400px] border-2 border-[#18181b] rounded' placeholder='Name'></input>
              <input className='p-2 w-full md:w-[400px] border-2 border-[#18181b] rounded' placeholder='Enter Email'></input>
              <textarea rows={4} className='p-2 w-full md:w-[400px] border-2 border-[#18181b] rounded' placeholder='Your Message'></textarea>
              <div className='flex w-full justify-end'>
                <button className='p-2 px-4 bg-green-500 rounded font-semibold text-white'>SUBMIT</button>
              </div>
            </div>
          </div>
        </div>
        <div className='h-40 w-screen bg-[#18181b] flex justify-center items-center gap-4 relative'>
          <div className='absolute inset-0 flex justify-center z-0'>
            <div onClick={()=>{mainref.current?.scrollTo(0,0)}} className='cursor-pointer w-12 h-14 box-cst2 flex z-10 justify-center items-center text-[#18181b] group hover:bg-sky-500 transition-all rounded-md relative -mt-[29px] after:z-0 after:opacity-30 after:w-12 after:h-14 after:rounded after:animate-ping after:box-cst2 after:absolute after:inset-0'>
              <Icon name="FaAngleDoubleUp" className='-mb-2 animate-bounce' size={28}/>
            </div>
          </div>
          <a target="_blank" href="https://www.linkedin.com/in/andy-khu-48562a140" rel="noopener noreferrer" className='z-10'>
            <div className='w-14 h-14 bg-[#262f38] flex justify-center items-center text-white group hover:bg-sky-500 transition-all rounded-md'>
              <Icon name="FaLinkedinIn" className='group-hover:animate-bounce' size={28}/>
            </div>
          </a>
          <a target="_blank" href="https://www.instagram.com/andy_khu/" rel="noopener noreferrer" className='z-10'>
            <div className='w-14 h-14 bg-[#262f38] flex justify-center items-center text-white group hover:bg-sky-500 transition-all rounded-md'>
              <Icon name="FaInstagram" className='group-hover:animate-bounce' size={28}/>
            </div>
          </a>
          <a target="_blank" href="https://www.facebook.com/andyandykhu/" rel="noopener noreferrer" className='z-10'>
            <div className='w-14 h-14 bg-[#262f38] flex justify-center items-center text-white group hover:bg-sky-500 transition-all rounded-md'>
              <Icon name="FaFacebookF" className='group-hover:animate-bounce' size={28}/>
            </div>
          </a>
        </div>
      </main>
    </>
  )
}
